// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "get": {
                tags: ["user"],
                "description": "usersの一覧を取得",
                "responses": {
                    "200": {
                        "description": "usersの一覧の取得",
                    }
                }
            },
        },
        "/users/{grade_id}/{department_id}/{bureau_id}/{role_id}": {
            "post": {
                tags: ["user"],
                "description": "userをcreate",
                "responses": {
                    "200": {
                        "description": "createしたuserのnameが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "name",
                        "in": "query",
                        "description": "name",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "mail",
                        "in": "query",
                        "description": "mail",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "student_number",
                        "in": "query",
                        "description": "student_number",
                        "type": "integer",
                        "required": true,
                    },
                    {
                        "name": "grade_id",
                        "in": "path",
                        "description": "grade_id",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "bureau_id",
                        "in": "path",
                        "description": "bureau_id",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "department_id",
                        "in": "path",
                        "description": "department_id",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "role_id",
                        "in": "path",
                        "description": "role_id",
                        "type": "integer",
                        "required": true,
                    },
                    {
                        "name": "tel",
                        "in": "query",
                        "description": "tel",
                        "type": "string",
                        "required": true,
                    },
                    {
                        "name": "password",
                        "in": "query",
                        "description": "password",
                        "type": "string",
                        "required": true,
                    }
                ]
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0",
	Host:             "localhost:1234",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "NUTFes SeeFT API",
	Description:      "SeeFT API ドキュメント",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
