// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "get": {
                tags: ["user"],
                "description": "usersの一覧を取得",
                "responses": {
                    "200": {
                        "description": "usersの一覧の取得",
                    }
                }
            },
            "post": {
                tags: ["user"],
                "description": "userをcreate",
                "responses": {
                    "200": {
                        "description": "createしたuserが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "name",
                        "in": "query",
                        "description": "name",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "mail",
                        "in": "query",
                        "description": "mail",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "student_number",
                        "in": "query",
                        "description": "student_number",
                        "type": "integer",
                        "required": true,
                    },
                    {
                        "name": "grade_id",
                        "in": "query",
                        "description": "grade_id",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "bureau_id",
                        "in": "query",
                        "description": "bureau_id",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "department_id",
                        "in": "query",
                        "description": "department_id",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "role_id",
                        "in": "query",
                        "description": "role_id",
                        "type": "integer",
                        "required": true,
                    },
                    {
                        "name": "tel",
                        "in": "query",
                        "description": "tel",
                        "type": "string",
                        "required": true,
                    },
                    {
                        "name": "password",
                        "in": "query",
                        "description": "password",
                        "type": "string",
                        "required": true,
                    }
                ]
            }
        },
        "/grades": {
            "get": {
                tags: ["grade"],
                "description": "gradesの一覧を取得",
                "responses": {
                    "200": {
                        "description": "gradesの一覧の取得",
                    }
                }
            }
        },
        "/departments": {
            "get": {
                tags: ["department"],
                "description": "departmentsの一覧を取得",
                "responses": {
                    "200": {
                        "description": "departmentsの一覧を取得",
                    }
                }
            }
        },
        "/bureaus": {
            "get": {
                tags: ["bureau"],
                "description": "bureausの一覧を取得",
                "responses": {
                    "200": {
                        "description": "bureausの一覧を取得",
                    }
                }
            }
        },
        "/shifts": {
            "get": {
                tags: ["shift"],
                "description": "shiftsの一覧を取得",
                "responses": {
                    "200": {
                        "description": "shiftsの一覧を取得",
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                tags: ["task"],
                "description": "tasksの一覧を取得",
                "responses": {
                    "200": {
                        "description": "tasksの一覧を取得",
                    }
                }
            },
            "post": {
                tags: ["task"],
                "description": "taskをcreate",
                "responses": {
                    "200": {
                        "description": "createしたtaskが返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "task",
                        "in": "query",
                        "description": "task",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "place_id",
                        "in": "query",
                        "description": "place_id",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "url",
                        "in": "query",
                        "description": "url",
                        "type": "string",
                        "required": true,
                    },
                    {
                        "name": "bureau_id",
                        "in": "query",
                        "description": "bureau_id",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "max_member",
                        "in": "query",
                        "description": "max_member",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "color",
                        "in": "query",
                        "description": "color",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "remark",
                        "in": "query",
                        "description": "remark",
                        "type": "string",
                        "required": false
                    },
                    {
                        "name": "year_id",
                        "in": "query",
                        "description": "year_id",
                        "type": "integer",
                        "required": true
                    }
                ]
            }
        },
        "/times": {
            "get": {
                tags: ["time"],
                "description": "timesの一覧を取得",
                "responses": {
                    "200": {
                        "description": "timesの一覧を取得",
                    }
                }
            }
        },
        "/rescues": {
            "get": {
                tags: ["rescue"],
                "description": "全ての統一レスキューの一覧を取得",
                "produces": ["application/json"],
                "responses": {
                    "200": {
                        "description": "レスキュー一覧の取得成功",
                    },
                    "500": {
                        "description": "サーバーエラー",
                    }
                }
            },
            "post": {
                tags: ["rescue"],
                "description": "統一されたレスキューリクエストを作成（trouble/question/shorthandedの3種類に対応）",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "responses": {
                    "201": {
                        "description": "レスキューリクエストが正常に作成されました",
                    },
                    "400": {
                        "description": "リクエストデータが不正です",
                    },
                    "500": {
                        "description": "サーバーエラー",
                    }
                },
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "description": "レスキューリクエストデータ",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string",
                                    "enum": ["trouble", "question", "shorthanded"],
                                    "description": "レスキューの種類"
                                },
                                "user_id": {
                                    "type": "integer",
                                    "description": "送信者のユーザーID"
                                },
                                "time": {
                                    "type": "string",
                                    "description": "発生時刻（YYYY/MM/DD hh:mm:ss形式）"
                                },
                                "content": {
                                    "type": "object",
                                    "description": "レスキューの詳細内容（typeによって構造が異なる）"
                                }
                            },
                            "required": ["type", "user_id", "content"]
                        }
                    }
                ]
            }
        },
        "/rescues/users/{user_id}": {
            "get": {
                tags: ["rescue"],
                "description": "特定ユーザーの統一レスキューの一覧を取得",
                "produces": ["application/json"],
                "responses": {
                    "200": {
                        "description": "ユーザー別レスキュー一覧の取得成功",
                    },
                    "400": {
                        "description": "ユーザーIDが不正です",
                    },
                    "500": {
                        "description": "サーバーエラー",
                    }
                },
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "path",
                        "description": "ユーザーID",
                        "type": "integer",
                        "required": true
                    }
                ]
            }
        },
        "/question-rescues": {
            "get": {
                tags: ["question-rescue"],
                "description": "質問救助の一覧を取得",
                "responses": {
                    "200": {
                        "description": "質問救助の一覧を取得",
                    }
                }
            },
            "post": {
                tags: ["question-rescue"],
                "description": "質問救助を作成",
                "responses": {
                    "201": {
                        "description": "作成した質問救助が返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "formData",
                        "description": "ユーザーID",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "question",
                        "in": "formData",
                        "description": "質問内容",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "status",
                        "in": "formData",
                        "description": "ステータス（todo/in_progress/done）",
                        "type": "string",
                        "required": false
                    }
                ]
            },
            "delete": {
                tags: ["question-rescue"],
                "description": "質問救助を削除",
                "responses": {
                    "200": {
                        "description": "削除成功",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "formData",
                        "description": "質問救助ID",
                        "type": "integer",
                        "required": true
                    }
                ]
            }
        },
        "/question-rescues/{id}": {
            "get": {
                tags: ["question-rescue"],
                "description": "質問救助の詳細を取得",
                "responses": {
                    "200": {
                        "description": "質問救助の詳細を取得",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "質問救助ID",
                        "type": "integer",
                        "required": true
                    }
                ]
            },
            "put": {
                tags: ["question-rescue"],
                "description": "質問救助を更新",
                "responses": {
                    "200": {
                        "description": "更新した質問救助が返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "質問救助ID",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "status",
                        "in": "formData",
                        "description": "ステータス（todo/in_progress/done）",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "response",
                        "in": "formData",
                        "description": "回答内容",
                        "type": "string",
                        "required": false
                    }
                ]
            }
        },
        "/question-rescues/users/{user_id}": {
            "get": {
                tags: ["question-rescue"],
                "description": "ユーザー別質問救助の一覧を取得",
                "responses": {
                    "200": {
                        "description": "ユーザー別質問救助の一覧を取得",
                    }
                },
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "path",
                        "description": "ユーザーID",
                        "type": "integer",
                        "required": true
                    }
                ]
            }
        },
        "/shorthanded-rescues": {
            "get": {
                tags: ["shorthanded-rescue"],
                "description": "人手不足救助の一覧を取得",
                "responses": {
                    "200": {
                        "description": "人手不足救助の一覧を取得",
                    }
                }
            },
            "post": {
                tags: ["shorthanded-rescue"],
                "description": "人手不足救助を作成",
                "responses": {
                    "201": {
                        "description": "作成した人手不足救助が返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "formData",
                        "description": "ユーザーID",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "task_id",
                        "in": "formData",
                        "description": "タスクID",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "missing_number",
                        "in": "formData",
                        "description": "不足人数",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "place",
                        "in": "formData",
                        "description": "場所",
                        "type": "string",
                        "required": false
                    },
                    {
                        "name": "status",
                        "in": "formData",
                        "description": "ステータス（todo/in_progress/done）",
                        "type": "string",
                        "required": false
                    }
                ]
            },
            "delete": {
                tags: ["shorthanded-rescue"],
                "description": "人手不足救助を削除",
                "responses": {
                    "200": {
                        "description": "削除成功",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "formData",
                        "description": "人手不足救助ID",
                        "type": "integer",
                        "required": true
                    }
                ]
            }
        },
        "/shorthanded-rescues/{id}": {
            "get": {
                tags: ["shorthanded-rescue"],
                "description": "人手不足救助の詳細を取得",
                "responses": {
                    "200": {
                        "description": "人手不足救助の詳細を取得",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "人手不足救助ID",
                        "type": "integer",
                        "required": true
                    }
                ]
            },
            "put": {
                tags: ["shorthanded-rescue"],
                "description": "人手不足救助を更新",
                "responses": {
                    "200": {
                        "description": "更新した人手不足救助が返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "人手不足救助ID",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "status",
                        "in": "formData",
                        "description": "ステータス（todo/in_progress/done）",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "response",
                        "in": "formData",
                        "description": "回答内容",
                        "type": "string",
                        "required": false
                    }
                ]
            }
        },
        "/shorthanded-rescues/users/{user_id}": {
            "get": {
                tags: ["shorthanded-rescue"],
                "description": "ユーザー別人手不足救助の一覧を取得",
                "responses": {
                    "200": {
                        "description": "ユーザー別人手不足救助の一覧を取得",
                    }
                },
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "path",
                        "description": "ユーザーID",
                        "type": "integer",
                        "required": true
                    }
                ]
            }
        },
        "/shorthanded-rescues/tasks/{task_id}": {
            "get": {
                tags: ["shorthanded-rescue"],
                "description": "タスク別人手不足救助の一覧を取得",
                "responses": {
                    "200": {
                        "description": "タスク別人手不足救助の一覧を取得",
                    }
                },
                "parameters": [
                    {
                        "name": "task_id",
                        "in": "path",
                        "description": "タスクID",
                        "type": "integer",
                        "required": true
                    }
                ]
            }
        },
        "/trouble-rescues": {
            "get": {
                tags: ["trouble-rescue"],
                "description": "トラブル救助の一覧を取得",
                "responses": {
                    "200": {
                        "description": "トラブル救助の一覧を取得",
                    }
                }
            },
            "post": {
                tags: ["trouble-rescue"],
                "description": "トラブル救助を作成",
                "responses": {
                    "201": {
                        "description": "作成したトラブル救助が返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "formData",
                        "description": "ユーザーID",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "task_id",
                        "in": "formData",
                        "description": "タスクID",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "place",
                        "in": "formData",
                        "description": "場所",
                        "type": "string",
                        "required": false
                    },
                    {
                        "name": "detail",
                        "in": "formData",
                        "description": "トラブル詳細",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "status",
                        "in": "formData",
                        "description": "ステータス（todo/in_progress/done）",
                        "type": "string",
                        "required": false
                    }
                ]
            },
            "delete": {
                tags: ["trouble-rescue"],
                "description": "トラブル救助を削除",
                "responses": {
                    "200": {
                        "description": "削除成功",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "formData",
                        "description": "トラブル救助ID",
                        "type": "integer",
                        "required": true
                    }
                ]
            }
        },
        "/trouble-rescues/{id}": {
            "get": {
                tags: ["trouble-rescue"],
                "description": "トラブル救助の詳細を取得",
                "responses": {
                    "200": {
                        "description": "トラブル救助の詳細を取得",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "トラブル救助ID",
                        "type": "integer",
                        "required": true
                    }
                ]
            },
            "put": {
                tags: ["trouble-rescue"],
                "description": "トラブル救助を更新",
                "responses": {
                    "200": {
                        "description": "更新したトラブル救助が返ってくる",
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "トラブル救助ID",
                        "type": "integer",
                        "required": true
                    },
                    {
                        "name": "status",
                        "in": "formData",
                        "description": "ステータス（todo/in_progress/done）",
                        "type": "string",
                        "required": true
                    },
                    {
                        "name": "response",
                        "in": "formData",
                        "description": "回答内容",
                        "type": "string",
                        "required": false
                    }
                ]
            }
        },
        "/trouble-rescues/users/{user_id}": {
            "get": {
                tags: ["trouble-rescue"],
                "description": "ユーザー別トラブル救助の一覧を取得",
                "responses": {
                    "200": {
                        "description": "ユーザー別トラブル救助の一覧を取得",
                    }
                },
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "path",
                        "description": "ユーザーID",
                        "type": "integer",
                        "required": true
                    }
                ]
            }
        },
        "/trouble-rescues/tasks/{task_id}": {
            "get": {
                tags: ["trouble-rescue"],
                "description": "タスク別トラブル救助の一覧を取得",
                "responses": {
                    "200": {
                        "description": "タスク別トラブル救助の一覧を取得",
                    }
                },
                "parameters": [
                    {
                        "name": "task_id",
                        "in": "path",
                        "description": "タスクID",
                        "type": "integer",
                        "required": true
                    }
                ]
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0",
	Host:             "localhost:1234",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "NUTFes SeeFT API",
	Description:      "SeeFT API ドキュメント",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
