version: "3.8"

services:
  db:
    container_name: nutfes-seeft-db
    image: mysql:8.0
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d # 初期データ
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: seeft_db
      MYSQL_USER: seeft
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    restart: always

  api:
    container_name: nutfes-seeft-api
    build: ./api
    restart: always
    volumes:
      - ./api:/app
    environment:
      MYSQL_DATABASE: seeft_db
      MYSQL_HOST: nutfes-seeft-db
      MYSQL_USER: seeft
      MYSQL_PASSWORD: password
    #シェルスクリプトを実行するコマンド
    command: "./start.sh"
    ports:
      - "1234:1234"
    stdin_open: true
    tty: true
    depends_on:
      db: 
        condition: service_started
  
  mobile:
    container_name: nutfes-seeft-mobile
    build: ./seeft-mobile
    volumes:
      - ./seeft-mobile:/app
    ports:
      - 3000:3000
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      api: 
        condition: service_started


