CREATE TABLE IF NOT EXISTS trouble_rescues (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    task_id INTEGER NOT NULL,
    place VARCHAR(255),
    detail VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'todo',
    response VARCHAR(255),
    time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE,
    FOREIGN KEY (task_id) REFERENCES tasks (id) ON UPDATE CASCADE
);