CREATE TABLE IF NOT EXISTS question_rescues (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    question VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'todo',
    response VARCHAR(255),
    time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE
);