name: CI

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT || github.token }}

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:ci

      - name: Configure Insecure Registry
        run: |
          sudo service docker stop
          echo "{\"insecure-registries\": [\"${{ secrets.HARBOR_REG }}\"]}" | sudo tee /etc/docker/daemon.json
          sudo service docker start

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          config-inline: |
            [registry."${{ secrets.HARBOR_REG }}"]
              http = true
              insecure = true

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REG }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASS }}

      - name: Create .env file
        run: |
          mkdir -p mobile/env
          printf '%s' "${{ secrets.SEEFT_MOBILE_ENVS }}" > mobile/env/.env

      - name: Build and Push API
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/prod.Dockerfile
          push: true
          tags: ${{ secrets.HARBOR_REG }}/seeft/api:latest
          cache-from: type=gha

      - name: Build and Push Admin
        uses: docker/build-push-action@v5
        with:
          context: ./admin
          file: ./admin/prod.Dockerfile
          push: true
          tags: ${{ secrets.HARBOR_REG }}/seeft/admin:latest
          cache-from: type=gha

      - name: Build and Push Mobile
        uses: docker/build-push-action@v5
        with:
          context: ./mobile
          file: ./mobile/Dockerfile
          push: true
          tags: ${{ secrets.HARBOR_REG }}/seeft/mobile:latest
          cache-from: type=gha

  trigger-cd:
    needs: build-and-push
    uses: ./.github/workflows/CD.yml
    secrets: inherit