name: flutter-lint

on:
  pull_request:
    paths:
      - "mobile/**"

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          flutter-version: 3.27.3
          channel: stable
          cache: true
      - name: flutter pub get
        run: flutter pub get
      - name: flutter analyze
        run: flutter analyze --fatal-infos
